/*
 * generated by Xtext 2.14.0
 */
package fr.inria.kairos.tuto.concretesyntax.xtext.ide


/**
 * Use this class to register ide components.
 */
class KairosSystemIdeModule extends AbstractKairosSystemIdeModule {
}
