/**
 * generated by Xtext 2.14.0
 */
package fr.inria.kairos.tuto.concretesyntax.xtext;

import fr.inria.kairos.tuto.concretesyntax.xtext.AbstractKairosSystemRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class KairosSystemRuntimeModule extends AbstractKairosSystemRuntimeModule {
}
