/**
 * generated by Xtext 2.14.0
 */
package fr.inria.kairos.tuto.concretesyntax.xtext;

import fr.inria.kairos.tuto.concretesyntax.xtext.KairosSystemStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class KairosSystemStandaloneSetup extends KairosSystemStandaloneSetupGenerated {
  public static void doSetup() {
    new KairosSystemStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
