/**
 * generated by Xtext 2.14.0
 */
package fr.inria.kairos.tuto.concretesyntax.xtext.ui.contentassist;

import fr.inria.kairos.tuto.concretesyntax.xtext.ui.contentassist.AbstractKairosSystemProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class KairosSystemProposalProvider extends AbstractKairosSystemProposalProvider {
}
