/*
 * generated by Xtext 2.14.0
 */
package fr.inria.kairos.tuto.concretesyntax.xtext


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class KairosSystemRuntimeModule extends AbstractKairosSystemRuntimeModule {
}
