/*
 * generated by Xtext 2.14.0
 */
package fr.inria.kairos.tuto.concretesyntax.xtext.parser.antlr;

import com.google.inject.Inject;
import fr.inria.kairos.tuto.concretesyntax.xtext.parser.antlr.internal.InternalKairosSystemParser;
import fr.inria.kairos.tuto.concretesyntax.xtext.services.KairosSystemGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class KairosSystemParser extends AbstractAntlrParser {

	@Inject
	private KairosSystemGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalKairosSystemParser createParser(XtextTokenStream stream) {
		return new InternalKairosSystemParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "KairosSystem";
	}

	public KairosSystemGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(KairosSystemGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
