/**
 * generated by Xtext 2.14.0
 */
package fr.inria.kairos.tuto.concretesyntax.xtext.ui;

import fr.inria.kairos.tuto.concretesyntax.xtext.ui.AbstractKairosSystemUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class KairosSystemUiModule extends AbstractKairosSystemUiModule {
  public KairosSystemUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
