/*
 * generated by Xtext 2.14.0
 */
package fr.inria.kairos.tuto.concretesyntax.xtext.ui.tests;

import com.google.inject.Injector;
import fr.inria.kairos.tuto.concretesyntax.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class KairosSystemUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("fr.inria.kairos.tuto.concretesyntax.xtext.KairosSystem");
	}

}
