/**
 * generated by Xtext 2.14.0
 */
package fr.inria.kairos.tuto.concretesyntax.xtext.ide;

import fr.inria.kairos.tuto.concretesyntax.xtext.ide.AbstractKairosSystemIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class KairosSystemIdeModule extends AbstractKairosSystemIdeModule {
}
