/**
 * generated by Xtext 2.14.0
 */
package fr.inria.kairos.tuto.concretesyntax.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.inria.kairos.tuto.concretesyntax.xtext.KairosSystemRuntimeModule;
import fr.inria.kairos.tuto.concretesyntax.xtext.KairosSystemStandaloneSetup;
import fr.inria.kairos.tuto.concretesyntax.xtext.ide.KairosSystemIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class KairosSystemIdeSetup extends KairosSystemStandaloneSetup {
  @Override
  public Injector createInjector() {
    KairosSystemRuntimeModule _kairosSystemRuntimeModule = new KairosSystemRuntimeModule();
    KairosSystemIdeModule _kairosSystemIdeModule = new KairosSystemIdeModule();
    return Guice.createInjector(Modules2.mixin(_kairosSystemRuntimeModule, _kairosSystemIdeModule));
  }
}
